# Generated by Django 4.0.3 on 2022-03-25 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolioapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
